from __future__ import annotations

from pathlib import Path

import yaml
from typer.testing import CliRunner

from envctl.cli.app import app


def test_sync_and_export_use_explicit_profile_values(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["profile", "create", "staging"], catch_exceptions=False)

    runner.invoke(
        app,
        ["--profile", "staging", "set", "APP_NAME", "demo-staging"],
        catch_exceptions=False,
    )
    runner.invoke(
        app,
        ["--profile", "staging", "set", "PORT", "3000"],
        catch_exceptions=False,
    )
    runner.invoke(
        app,
        ["--profile", "staging", "set", "DATABASE_URL", "https://db.example.com"],
        catch_exceptions=False,
    )

    sync = runner.invoke(app, ["--profile", "staging", "sync"], catch_exceptions=False)
    assert sync.exit_code == 0
    assert "profile: staging" in sync.stdout

    env_file = workspace / ".env.staging"
    assert env_file.exists()
    content = env_file.read_text(encoding="utf-8")
    assert "APP_NAME=demo-staging" in content
    assert "PORT=3000" in content
    assert "DATABASE_URL=https://db.example.com" in content

    export = runner.invoke(app, ["--profile", "staging", "export"], catch_exceptions=False)
    assert export.exit_code == 0
    assert "profile: staging" in export.stdout
    assert "export APP_NAME='demo-staging'" in export.stdout


def test_run_uses_explicit_profile_values(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["profile", "create", "dev"], catch_exceptions=False)

    runner.invoke(
        app,
        ["--profile", "dev", "set", "APP_NAME", "demo-dev"],
        catch_exceptions=False,
    )
    runner.invoke(
        app,
        ["--profile", "dev", "set", "DATABASE_URL", "postgres://user:pass@localhost:5432/app"],
        catch_exceptions=False,
    )

    output_path = workspace / "profile-run.txt"
    script = (
        "from pathlib import Path; "
        "import os; "
        f"Path({str(output_path)!r}).write_text("
        "os.getenv('APP_NAME', ''), encoding='utf-8')"
    )

    result = runner.invoke(
        app,
        ["--profile", "dev", "run", "python3", "-c", script],
    )

    assert result.exit_code == 0
    assert output_path.read_text(encoding="utf-8") == "demo-dev"


def test_sync_and_run_apply_group_filter_to_projection_outputs(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    contract_path = workspace / ".envctl.yaml"
    contract = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    contract["variables"]["APP_NAME"]["group"] = "Application"
    contract["variables"]["PORT"]["group"] = "Runtime"
    contract["variables"]["DATABASE_URL"]["group"] = "Database"
    contract_path.write_text(yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    sync = runner.invoke(
        app,
        ["--group", "Application", "sync"],
        catch_exceptions=False,
    )

    assert sync.exit_code == 0
    content = (workspace / ".env.local").read_text(encoding="utf-8")
    assert content == (
        "# Generated by envctl\n\n"
        "# ------------------------------------------------------------------\n"
        "# Application\n"
        "# ------------------------------------------------------------------\n"
        "APP_NAME=demo\n"
    )

    output_path = workspace / "grouped-run.json"
    script = (
        "from pathlib import Path; "
        "import json, os; "
        f"Path({str(output_path)!r}).write_text("
        "json.dumps({"
        "'APP_NAME': os.getenv('APP_NAME'), "
        "'PORT': os.getenv('PORT'), "
        "'DATABASE_URL': os.getenv('DATABASE_URL')"
        "}), encoding='utf-8')"
    )

    result = runner.invoke(
        app,
        ["--group", "Application", "run", "python3", "-c", script],
        catch_exceptions=False,
    )

    assert result.exit_code == 0
    assert output_path.read_text(encoding="utf-8") == (
        '{"APP_NAME": "demo", "PORT": null, "DATABASE_URL": null}'
    )


def test_run_failure_explains_group_filtered_projection_problem(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    contract_path = workspace / ".envctl.yaml"
    contract = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    contract["variables"]["APP_NAME"]["group"] = "Application"
    contract["variables"]["PORT"]["group"] = "Runtime"
    contract["variables"]["DATABASE_URL"]["group"] = "Database"
    contract["variables"]["APP_URL"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Application",
        "default": "http://${API_HOST}:${PORT}",
    }
    contract["variables"]["API_HOST"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Network",
    }
    contract_path.write_text(yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(
        app,
        ["--group", "Application", "run", "python3", "-V"],
        catch_exceptions=False,
    )

    assert result.exit_code == 1
    assert "Error: Cannot run because the environment contract is not satisfied." in result.output
    assert "scope: group=Application" in result.output
    assert "Invalid keys" in result.output
    assert "APP_URL" in result.output
    assert "Expansion reference error" in result.output
