from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from envctl.cli.app import app


def test_export_outputs_shell_lines(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(app, ["export"], catch_exceptions=False)

    assert result.exit_code == 0
    assert "profile: local" in result.stdout
    assert "export APP_NAME='demo'" in result.stdout
    assert "export PORT='3000'" in result.stdout
    assert "export DATABASE_URL='https://db.example.com'" in result.stdout


def test_export_shell_matches_default(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    default_result = runner.invoke(app, ["export"], catch_exceptions=False)
    shell_result = runner.invoke(app, ["export", "--format", "shell"], catch_exceptions=False)

    assert shell_result.exit_code == 0
    assert shell_result.stdout == default_result.stdout


def test_export_dotenv_prints_clean_dotenv_lines(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(app, ["export", "--format", "dotenv"], catch_exceptions=False)

    assert result.exit_code == 0
    assert result.stdout == (
        "APP_NAME=demo\nDATABASE_URL=https://db.example.com\nDEBUG=False\nPORT=3000\n"
    )
    assert "# Generated by envctl" not in result.stdout
    assert "export " not in result.stdout
