from __future__ import annotations

from pathlib import Path

import yaml
from typer.testing import CliRunner

from envctl.cli.app import app


def test_export_outputs_shell_lines(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(app, ["export"], catch_exceptions=False)

    assert result.exit_code == 0
    assert "profile: local" in result.stdout
    assert "export APP_NAME='demo'" in result.stdout
    assert "export PORT='3000'" in result.stdout
    assert "export DATABASE_URL='https://db.example.com'" in result.stdout


def test_export_shell_matches_default(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    default_result = runner.invoke(app, ["export"], catch_exceptions=False)
    shell_result = runner.invoke(app, ["export", "--format", "shell"], catch_exceptions=False)

    assert shell_result.exit_code == 0
    assert shell_result.stdout == default_result.stdout


def test_export_dotenv_prints_clean_dotenv_lines(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(app, ["export", "--format", "dotenv"], catch_exceptions=False)

    assert result.exit_code == 0
    assert result.stdout == "APP_NAME=demo\nDATABASE_URL=https://db.example.com\nPORT=3000\n"
    assert "# Generated by envctl" not in result.stdout
    assert "export " not in result.stdout


def test_export_dotenv_groups_and_filters_selected_group(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    schema_path = workspace / ".envctl.schema.yaml"
    schema = yaml.safe_load(schema_path.read_text(encoding="utf-8"))
    schema["variables"]["APP_NAME"]["group"] = "Application"
    schema["variables"]["PORT"]["group"] = "Runtime"
    schema["variables"]["DATABASE_URL"]["group"] = "Database"
    schema["variables"]["APP_URL"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Application",
        "default": "http://${APP_NAME}:${PORT}",
    }
    schema_path.write_text(yaml.safe_dump(schema, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(
        app,
        ["--group", "Application", "export", "--format", "dotenv"],
        catch_exceptions=False,
    )

    assert result.exit_code == 0
    assert result.stdout == (
        "# ------------------------------------------------------------------\n"
        "# Application\n"
        "# ------------------------------------------------------------------\n"
        "APP_NAME=demo\n"
        "APP_URL=http://demo:3000\n"
    )
