from __future__ import annotations

import json
from pathlib import Path

import yaml
from typer.testing import CliRunner

from envctl.cli.app import app


def get_fake_home(workspace: Path) -> Path:
    """Return the fake home directory used by CLI integration tests."""
    return workspace.parent / "home"


def get_vault_projects_dir(workspace: Path) -> Path:
    """Return the test vault projects directory."""
    return get_fake_home(workspace) / ".envctl" / "vault" / "projects"


def get_config_path(workspace: Path) -> Path:
    """Return the config file path inside the fake home directory."""
    return get_fake_home(workspace) / ".config" / "envctl" / "config.json"


def find_single_state_path(workspace: Path) -> Path:
    """Locate the single generated state.json file for the test workspace."""
    vault_projects_dir = get_vault_projects_dir(workspace)
    candidates = sorted(vault_projects_dir.glob("*/state.json"))

    matching = []
    for candidate in candidates:
        try:
            contents = json.loads(candidate.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            matching.append(candidate)
            continue

        if contents.get("repo_root") == str(workspace):
            matching.append(candidate)

    assert matching, f"No state.json found for workspace {workspace} under {vault_projects_dir}"
    assert len(matching) == 1, (
        f"Expected exactly one state.json for workspace {workspace}, "
        f"found {len(matching)}: {matching}"
    )
    return matching[0]


def normalize_output(value: str) -> str:
    """Normalize path separators in CLI output."""
    return value.replace("\\", "/")


def normalize_newlines(value: str) -> str:
    """Normalize Windows and Unix newlines for assertions."""
    return value.replace("\r\n", "\n")


def test_check_fails_when_required_value_is_missing(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    result = runner.invoke(app, ["check"], catch_exceptions=False)
    assert result.exit_code == 1
    assert "Missing required keys" in result.stdout


def test_set_check_and_sync(runner: CliRunner, workspace: Path) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    check = runner.invoke(app, ["check"], catch_exceptions=False)
    assert check.exit_code == 0
    assert "Environment contract satisfied" in check.stdout

    sync = runner.invoke(app, ["sync"], catch_exceptions=False)
    assert sync.exit_code == 0
    assert "Synced generated environment" in sync.stdout
    assert normalize_newlines((workspace / ".env.local").read_text(encoding="utf-8")) == (
        "# Generated by envctl\n\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\nPORT=3000\n"
    )


def test_sync_with_output_writes_custom_path_and_matches_dotenv_export(
    runner: CliRunner,
    workspace: Path,
) -> None:
    custom_path = workspace / "tmp.env"

    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    sync = runner.invoke(app, ["sync", "--output-path", str(custom_path)], catch_exceptions=False)
    export = runner.invoke(app, ["export", "--format", "dotenv"], catch_exceptions=False)

    assert sync.exit_code == 0
    assert "target: " + str(custom_path) in sync.stdout
    assert custom_path.exists()
    content = normalize_newlines(custom_path.read_text(encoding="utf-8"))
    assert content.startswith("# Generated by envctl\n\n")
    assert content.removeprefix("# Generated by envctl\n\n") == normalize_newlines(export.stdout)


def test_sync_failure_explains_missing_required_keys(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)
    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)

    result = runner.invoke(app, ["sync"], catch_exceptions=False)

    assert result.exit_code == 1
    assert "Error: Cannot sync because the environment contract is not satisfied." in result.output
    assert "Missing required keys" in result.output
    assert "DATABASE_URL" in result.output
    assert "Run `envctl fill`" in result.output
    assert "Run `envctl set KEY VALUE`" in result.output


def test_check_failure_explains_invalid_contract_file(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    contract_path = workspace / ".envctl.yaml"
    contract_path.write_text(":\n- bad", encoding="utf-8")

    result = runner.invoke(app, ["check"], catch_exceptions=False)

    assert result.exit_code == 1
    assert "Error: Invalid YAML contract:" in result.output
    assert f"path: {contract_path}" in result.output
    assert "Next steps" in result.output
    assert "Run `envctl check`" in result.output
    assert "Run `fix .envctl.yaml`" in result.output


def test_callback_failure_explains_invalid_config(
    runner: CliRunner,
    workspace: Path,
) -> None:
    config_path = get_config_path(workspace)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text('{"runtime_mode":"banana"}', encoding="utf-8")

    result = runner.invoke(app, ["check"], catch_exceptions=False)

    assert result.exit_code == 1
    assert "Error: Invalid runtime mode in config file:" in result.output
    assert f"path: {config_path}" in result.output
    assert "source: config file" in result.output


def test_status_failure_explains_corrupted_state_file(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    state_path = find_single_state_path(workspace)
    state_path.write_text("{not-json", encoding="utf-8")

    result = runner.invoke(app, ["status"], catch_exceptions=False)

    assert result.exit_code == 1
    assert "Error: State file is corrupted:" in result.output
    assert f"path: {state_path}" in result.output


def test_status_failure_explains_ambiguous_vault_identity(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)

    vault_projects_dir = get_vault_projects_dir(workspace)
    first = vault_projects_dir / "demo-a--prj_1111111111111111"
    second = vault_projects_dir / "demo-b--prj_2222222222222222"
    first.mkdir(parents=True, exist_ok=True)
    second.mkdir(parents=True, exist_ok=True)
    payload = (
        '{"version":2,"project_slug":"demo","project_key":"demo","project_id":"%s",'
        '"repo_root":"%s","git_remote":"git@github.com:labrynx/envctl.git",'
        '"known_paths":[],"created_at":"2026-03-30T00:00:00Z","last_seen_at":"2026-03-30T00:00:00Z"}'
    )
    (first / "state.json").write_text(
        payload % ("prj_1111111111111111", str(workspace)),
        encoding="utf-8",
    )
    (second / "state.json").write_text(
        payload % ("prj_2222222222222222", str(workspace)),
        encoding="utf-8",
    )

    result = runner.invoke(app, ["status"], catch_exceptions=False)

    assert result.exit_code == 1
    assert "Error: Ambiguous vault identity for this repository." in result.output
    assert f"repo_root: {workspace}" in result.output
    assert "matching_ids: prj_1111111111111111, prj_2222222222222222" in result.output
    assert "Run `envctl project bind`" in result.output


def test_check_fails_for_invalid_string_json_format(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    contract_path = workspace / ".envctl.yaml"
    contract = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    contract["variables"]["TEST_JSON"] = {
        "type": "string",
        "format": "json",
        "required": True,
        "sensitive": False,
    }
    contract_path.write_text(yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)
    runner.invoke(app, ["set", "TEST_JSON", '{\\"broken\\"}'], catch_exceptions=False)

    check = runner.invoke(app, ["check"], catch_exceptions=False)
    assert check.exit_code == 1
    assert "Invalid keys" in check.stdout
    assert "TEST_JSON: Expected a valid JSON string" in check.stdout


def test_add_format_json_persists_and_is_used_by_check(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "PORT", "3000"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)
    runner.invoke(
        app,
        ["add", "TEST_JSON", '{"ok": true}', "--type", "string", "--format", "json"],
        catch_exceptions=False,
    )

    contract = yaml.safe_load((workspace / ".envctl.yaml").read_text(encoding="utf-8"))
    assert contract["variables"]["TEST_JSON"]["format"] == "json"

    runner.invoke(app, ["set", "TEST_JSON", '{\\"broken\\"}'], catch_exceptions=False)
    check = runner.invoke(app, ["check"], catch_exceptions=False)
    assert check.exit_code == 1
    assert "TEST_JSON: Expected a valid JSON string" in check.stdout


def test_grouped_check_ignores_unrelated_missing_keys(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    contract_path = workspace / ".envctl.yaml"
    contract = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    contract["variables"]["APP_NAME"]["group"] = "Application"
    contract["variables"]["PORT"]["group"] = "Runtime"
    contract["variables"]["DATABASE_URL"]["group"] = "Database"
    contract["variables"]["APP_URL"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Application",
        "default": "http://${APP_NAME}:${PORT}",
    }
    contract_path.write_text(yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)

    result = runner.invoke(
        app,
        ["--group", "Application", "check"],
        catch_exceptions=False,
    )

    assert result.exit_code == 0
    assert "scope: group=Application" in result.stdout
    assert "Environment contract satisfied" in result.stdout


def test_grouped_check_fails_when_targeted_variable_has_missing_cross_group_reference(
    runner: CliRunner,
    workspace: Path,
) -> None:
    runner.invoke(app, ["config", "init"], catch_exceptions=False)
    runner.invoke(app, ["init", "--contract", "starter"], catch_exceptions=False)

    contract_path = workspace / ".envctl.yaml"
    contract = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    contract["variables"]["APP_NAME"]["group"] = "Application"
    contract["variables"]["PORT"]["group"] = "Runtime"
    contract["variables"]["DATABASE_URL"]["group"] = "Database"
    contract["variables"]["APP_URL"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Application",
        "default": "http://${API_HOST}:${PORT}",
    }
    contract["variables"]["API_HOST"] = {
        "type": "string",
        "required": True,
        "sensitive": False,
        "group": "Network",
    }
    contract_path.write_text(yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")

    runner.invoke(app, ["set", "APP_NAME", "demo"], catch_exceptions=False)
    runner.invoke(app, ["set", "DATABASE_URL", "https://db.example.com"], catch_exceptions=False)

    result = runner.invoke(
        app,
        ["--group", "Application", "check"],
        catch_exceptions=False,
    )

    assert result.exit_code == 1
    assert "APP_URL" in result.stdout
    assert "Expansion reference error" in result.stdout