"""Project-wide constants."""

APP_NAME = "envctl"

DEFAULT_ENV_FILENAME = ".env.local"
DEFAULT_SCHEMA_FILENAME = ".envctl.schema.yaml"
DEFAULT_STATE_FILENAME = "state.json"
DEFAULT_VALUES_FILENAME = "values.env"

DEFAULT_CONFIG_DIRNAME = "envctl"
DEFAULT_CONFIG_FILENAME = "config.json"
DEFAULT_PROJECTS_DIRNAME = "projects"

CONTRACT_VERSION = 1
STATE_VERSION = 1
PROJECT_ID_LENGTH = 12

MATERIALIZED_ENV_HEADER = "# Generated by envctl. Do not edit manually.\n"
