"""Project-wide constants."""

DEFAULT_ENV_FILENAME = ".env.local"
DEFAULT_KEY_FILENAME = "master.key"
DEFAULT_ENV_EXAMPLE_FILENAME = ".env.example"
DEFAULT_SCHEMA_FILENAME = ".envctl.schema.yaml"
DEFAULT_STATE_FILENAME = "state.json"
DEFAULT_VALUES_FILENAME = "values.env"

DEFAULT_CONFIG_DIRNAME = "envctl"
DEFAULT_CONFIG_FILENAME = "config.json"
DEFAULT_PROJECTS_DIRNAME = "projects"
DEFAULT_PROFILES_DIRNAME = "profiles"
DEFAULT_PROFILE = "local"

CONTRACT_VERSION = 1
STATE_VERSION = 2

PROJECT_ID_PREFIX = "prj_"
PROJECT_ID_HEX_LENGTH = 16
PROVISIONAL_PROJECT_ID_LENGTH = 12

GIT_CONFIG_PROJECT_ID_KEY = "envctl.projectId"

ENVCTL_RUNTIME_MODE_ENVVAR = "ENVCTL_RUNTIME_MODE"
ENVCTL_PROFILE_ENVVAR = "ENVCTL_PROFILE"
ENVCTL_VAULT_KEY_ENVVAR = "ENVCTL_VAULT_KEY"

VAULT_ENCRYPTION_FORMAT_VERSION = "ENVCTL-VAULT-V1"
