from __future__ import annotations

from envctl.adapters.dotenv import dump_env
from envctl.utils.projection_rendering import render_dotenv, render_shell_exports


def test_render_shell_exports_includes_export_prefix() -> None:
    rendered = render_shell_exports({"APP_NAME": "demo"})

    assert rendered == "export APP_NAME='demo'"


def test_render_dotenv_omits_export_prefix() -> None:
    rendered = render_dotenv({"APP_NAME": "demo"})

    assert "export " not in rendered
    assert rendered == "APP_NAME=demo\n"


def test_render_dotenv_without_header_has_no_comment_line() -> None:
    rendered = render_dotenv({"APP_NAME": "demo"})

    assert not rendered.startswith("#")


def test_render_dotenv_with_header_includes_generated_comment() -> None:
    rendered = render_dotenv({"APP_NAME": "demo"}, include_header=True)

    assert rendered.startswith("# Generated by envctl\n")


def test_render_dotenv_matches_dump_env_for_quoting_edge_cases() -> None:
    values = {
        "BACKSLASH": r"C:\tmp\demo",
        "EMPTY": "",
        "QUOTES": 'say "hi"',
        "SPACES": "demo app",
    }

    assert render_dotenv(values) == dump_env(values)
