from __future__ import annotations

from pathlib import Path

from envctl.adapters.dotenv import dump_env, load_env_file, parse_env_text


def test_parse_env_text_ignores_comments_blank_lines_and_invalid_lines() -> None:
    content = """
# comment
APP_NAME="demo"

INVALID_LINE
 =ignored
PORT=3000
DEBUG='true'
"""

    result = parse_env_text(content)

    assert result == {
        "APP_NAME": "demo",
        "PORT": "3000",
        "DEBUG": "true",
    }


def test_parse_env_text_keeps_unquoted_values() -> None:
    content = "APP_NAME=demo\nURL=https://example.com\n"

    result = parse_env_text(content)

    assert result == {
        "APP_NAME": "demo",
        "URL": "https://example.com",
    }


def test_load_env_file_returns_empty_mapping_when_file_is_missing(tmp_path: Path) -> None:
    target = tmp_path / "missing.env"

    assert load_env_file(target) == {}


def test_load_env_file_parses_existing_file(tmp_path: Path) -> None:
    target = tmp_path / "values.env"
    target.write_text('APP_NAME="demo"\nPORT=3000\n', encoding="utf-8")

    assert load_env_file(target) == {
        "APP_NAME": "demo",
        "PORT": "3000",
    }


def test_dump_env_serializes_sorted_keys_and_optional_header() -> None:
    result = dump_env(
        {
            "PORT": "3000",
            "APP_NAME": 'demo "app"',
            "WINDOWS_PATH": r"C:\temp\demo",
        },
        header="# Generated by envctl\n",
    )

    expected = "\n".join(
        [
            "# Generated by envctl",
            "",
            'APP_NAME="demo \\"app\\""',
            "PORT=3000",
            r"WINDOWS_PATH=C:\temp\demo",
            "",
        ]
    )

    assert result == expected


def test_dump_env_without_header_still_ends_with_newline_block() -> None:
    result = dump_env({"APP_NAME": "demo"})

    assert result == "APP_NAME=demo\n"


def test_dump_env_quotes_empty_values() -> None:
    result = dump_env({"EMPTY": ""})

    assert result == 'EMPTY=""\n'


def test_dump_env_quotes_values_with_spaces() -> None:
    result = dump_env({"APP_NAME": "demo app"})

    assert result == 'APP_NAME="demo app"\n'


def test_dump_env_quotes_values_with_hash_character() -> None:
    result = dump_env({"PASSWORD": "abc#123"})

    assert result == 'PASSWORD="abc#123"\n'


def test_parse_env_text_unescapes_supported_double_quoted_sequences() -> None:
    content = 'VALUE="a\\\\b \\"q\\" \\$HOME \\`cmd\\`"\n'

    result = parse_env_text(content)

    assert result == {"VALUE": 'a\\b "q" $HOME `cmd`'}


def test_parse_env_text_roundtrip_keeps_json_array_logical_value() -> None:
    source = {"TEST_JSON": '["one","two"]', "OTHER": "1234"}

    first_dump = dump_env(source)
    parsed = parse_env_text(first_dump)
    second_dump = dump_env(parsed)
    reparsed = parse_env_text(second_dump)

    assert parsed["TEST_JSON"] == '["one","two"]'
    assert reparsed["TEST_JSON"] == '["one","two"]'
    assert reparsed == source


def test_parse_env_text_roundtrip_keeps_json_object_logical_value() -> None:
    source = {"TEST_JSON": '{"bootstrap": true, "owner": "contextd"}'}

    dumped = dump_env(source)
    reparsed = parse_env_text(dumped)

    assert reparsed == source


def test_parse_dump_cycles_are_idempotent_for_escaped_values() -> None:
    expected = {
        "TEST_REGEX": '["core.*","evolution.signal.reported.v1"]',
        "WINDOWS_PATH": r"C:\temp\demo",
        "QUOTED": 'say "hello"',
    }

    current = dict(expected)
    for _ in range(5):
        current = parse_env_text(dump_env(current))

    assert current == expected
