from envctl.adapters.dotenv import dump_env
from envctl.utils.shells import to_shell_export_lines

_HEADER = "# Generated by envctl\n"


def render_shell_exports(values: dict[str, str]) -> str:
    return "".join(to_shell_export_lines(values))


def render_dotenv(values: dict[str, str], *, include_header: bool = False) -> str:
    header = _HEADER if include_header else ""
    return dump_env(values, header=header)
