from __future__ import annotations

from collections.abc import Mapping

from envctl.adapters.dotenv import dump_env
from envctl.utils.shells import to_shell_export_lines

_HEADER = "# Generated by envctl\n"
_SECTION_RULE = "# ------------------------------------------------------------------"


def render_shell_exports(values: dict[str, str]) -> str:
    return "".join(to_shell_export_lines(values))


def _render_grouped_dotenv_body(
    values: Mapping[str, str],
    *,
    variable_groups: Mapping[str, str | None],
) -> str:
    ungrouped: dict[str, str] = {}
    grouped: dict[str, dict[str, str]] = {}
    group_order: list[str] = []

    for key in sorted(values):
        group = variable_groups.get(key)
        if group is None:
            ungrouped[key] = values[key]
            continue

        if group not in grouped:
            grouped[group] = {}
            group_order.append(group)
        grouped[group][key] = values[key]

    sections: list[str] = []

    if ungrouped:
        sections.append(dump_env(ungrouped).rstrip("\n"))

    for group in group_order:
        section_lines = [
            _SECTION_RULE,
            f"# {group}",
            _SECTION_RULE,
            dump_env(grouped[group]).rstrip("\n"),
        ]
        sections.append("\n".join(section_lines))

    if not sections:
        return ""

    return "\n\n".join(sections) + "\n"


def render_dotenv(
    values: dict[str, str],
    *,
    include_header: bool = False,
    variable_groups: Mapping[str, str | None] | None = None,
) -> str:
    header = _HEADER if include_header else ""
    normalized_groups = variable_groups or {}
    if variable_groups is not None and not values:
        return _HEADER if include_header else ""

    if not any(group is not None for group in normalized_groups.values()):
        return dump_env(values, header=header)

    body = _render_grouped_dotenv_body(values, variable_groups=normalized_groups)
    if not include_header:
        return body

    if not body:
        return _HEADER

    return f"{_HEADER}\n{body}"
