"""Sync service."""

from __future__ import annotations

from pathlib import Path

from envctl.adapters.dotenv import dump_env
from envctl.domain.project import ProjectContext
from envctl.errors import ValidationError
from envctl.services.context_service import load_project_context
from envctl.services.resolution_service import (
    load_contract_for_context,
    resolve_environment,
)
from envctl.utils.atomic import write_text_atomic
from envctl.utils.project_paths import normalize_profile_name


def run_sync(
    active_profile: str | None = None,
) -> tuple[ProjectContext, str, Path]:
    """Materialize the resolved environment into the repository env file."""
    _config, context = load_project_context()
    resolved_profile = normalize_profile_name(active_profile)

    contract = load_contract_for_context(context)
    report = resolve_environment(context, contract, active_profile=resolved_profile)

    if not report.is_valid:
        raise ValidationError("Environment contract is not satisfied")

    if report.unknown_keys:
        raise ValidationError("Vault contains unknown keys")

    values = {key: item.value for key, item in sorted(report.values.items())}

    rendered = dump_env(values, header="# Generated by envctl\n")
    write_text_atomic(context.repo_env_path, rendered)

    return context, resolved_profile, context.repo_env_path
