from __future__ import annotations

import pytest

import envctl.services.export_service as export_service
from envctl.domain.selection import group_selection
from envctl.errors import ValidationError
from tests.support.builders import make_resolution_report, make_resolved_value
from tests.support.contexts import make_project_context
from tests.support.contracts import make_contract, make_variable_spec
from tests.support.projection_validation import raise_projection_error


def test_run_export_returns_shell_lines_for_active_profile_by_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            ),
            "PORT": make_resolved_value(
                key="PORT",
                value="3000",
                source="default",
            ),
        },
    )
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME"),
            "PORT": make_variable_spec(name="PORT"),
        }
    )

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        export_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )

    _context, active_profile, values, rendered, warnings = export_service.run_export("staging")

    assert active_profile == "staging"
    assert warnings == ()
    assert values == {"APP_NAME": "demo", "PORT": "3000"}
    assert "export APP_NAME='demo'" in rendered
    assert "export PORT='3000'" in rendered


def test_run_export_returns_dotenv_without_header(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            )
        }
    )
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        export_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )

    _context, active_profile, values, rendered, warnings = export_service.run_export(
        "staging",
        format="dotenv",
    )

    assert active_profile == "staging"
    assert warnings == ()
    assert values == {"APP_NAME": "demo"}
    assert rendered == "APP_NAME=demo\n"
    assert "# Generated by envctl" not in rendered


def test_run_export_rejects_invalid_resolution(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    filtered_report = make_resolution_report(missing_required=("DATABASE_URL",))

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        export_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: raise_projection_error(
            operation=operation,
            profile=active_profile,
            selection=selection,
            report=filtered_report,
            suggested_actions=("envctl fill", "envctl set KEY VALUE"),
        ),
    )

    with pytest.raises(ValidationError, match=r"Cannot export because"):
        export_service.run_export("dev")


def test_run_export_projects_only_selected_group(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    contract = make_contract(
        {
            "API_HOST": make_variable_spec(name="API_HOST", groups=("Network",)),
            "API_URL": make_variable_spec(
                name="API_URL",
                groups=("Application",),
            ),
        }
    )
    report = make_resolution_report(
        values={
            "API_HOST": make_resolved_value(
                key="API_HOST",
                value="host",
                source="profile",
            ),
            "API_URL": make_resolved_value(
                key="API_URL",
                value="http://host",
                source="profile",
            ),
        },
    )

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        export_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )

    _context, _profile, values, rendered, _warnings = export_service.run_export(
        "staging",
        format="dotenv",
        selection=group_selection("Application"),
    )

    assert values == {"API_URL": "http://host"}
    assert rendered == (
        "# ------------------------------------------------------------------\n"
        "# Application\n"
        "# ------------------------------------------------------------------\n"
        "API_URL=http://host\n"
    )
