from __future__ import annotations

from pathlib import Path

import pytest

import envctl.services.sync_service as sync_service
from envctl.errors import ValidationError
from tests.support.builders import make_resolution_report, make_resolved_value
from tests.support.contexts import make_project_context


def test_run_sync_writes_generated_repo_env_file(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile"),
            "DATABASE_URL": make_resolved_value(
                key="DATABASE_URL",
                value="https://db.example.com",
                source="profile",
                masked=True,
            ),
        },
    )
    captured: dict[str, object] = {}

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(sync_service, "load_contract_for_context", lambda _context: object())
    monkeypatch.setattr(
        sync_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )
    monkeypatch.setattr(
        sync_service,
        "render_dotenv",
        lambda values, include_header=False: (
            "# Generated by envctl\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
            if include_header
            else "APP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
        ),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path = sync_service.run_sync("staging")

    assert active_profile == "staging"
    assert target_path == context.repo_root / ".env.staging"
    assert captured["path"] == context.repo_root / ".env.staging"
    assert (
        captured["text"]
        == "# Generated by envctl\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
    )


def test_run_sync_uses_custom_output_path_when_provided(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile")}
    )
    captured: dict[str, object] = {}
    output_path = Path("/tmp/custom/demo.env")

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(sync_service, "load_contract_for_context", lambda _context: object())
    monkeypatch.setattr(
        sync_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path = sync_service.run_sync(
        "staging",
        output_path=output_path,
    )

    assert active_profile == "staging"
    assert target_path == output_path
    assert captured["path"] == output_path
    assert captured["text"] == "# Generated by envctl\n\nAPP_NAME=demo\n"


def test_run_sync_body_matches_dotenv_export_except_for_header(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile"),
            "PORT": make_resolved_value(key="PORT", value="3000", source="default"),
        }
    )
    captured: dict[str, object] = {}

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(sync_service, "load_contract_for_context", lambda _context: object())
    monkeypatch.setattr(
        sync_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    sync_service.run_sync("staging")

    sync_text = captured["text"]
    assert isinstance(sync_text, str)
    assert sync_text.startswith("# Generated by envctl\n")
    assert sync_text.removeprefix("# Generated by envctl\n\n") == "APP_NAME=demo\nPORT=3000\n"


def test_run_sync_rejects_invalid_resolution(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(missing_required=("DATABASE_URL",))

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(sync_service, "load_contract_for_context", lambda _context: object())
    monkeypatch.setattr(
        sync_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )

    with pytest.raises(ValidationError, match="Environment contract is not satisfied"):
        sync_service.run_sync("dev")
