from __future__ import annotations

import pytest

import envctl.services.export_service as export_service
from envctl.errors import ValidationError
from tests.support.builders import make_resolution_report, make_resolved_value
from tests.support.contexts import make_project_context
from tests.support.contracts import make_contract, make_variable_spec


def test_run_export_returns_shell_lines_for_active_profile_by_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile"),
            "PORT": make_resolved_value(key="PORT", value="3000", source="default"),
        },
    )
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME"),
            "PORT": make_variable_spec(name="PORT"),
        }
    )

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )
    monkeypatch.setattr(
        export_service,
        "render_shell_exports",
        lambda values: "\n".join(f"export {key}='{value}'" for key, value in values.items()) + "\n",
    )

    _context, active_profile, rendered = export_service.run_export("staging")

    assert active_profile == "staging"
    assert "export APP_NAME='demo'" in rendered
    assert "export PORT='3000'" in rendered


def test_run_export_explicit_shell_matches_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile")}
    )
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )
    monkeypatch.setattr(
        export_service,
        "render_shell_exports",
        lambda values: "\n".join(f"export {key}='{value}'" for key, value in values.items()) + "\n",
    )

    default_result = export_service.run_export("staging")
    explicit_result = export_service.run_export("staging", format="shell")

    assert default_result == explicit_result


def test_run_export_returns_dotenv_without_header(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile")}
    )
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )

    _context, active_profile, rendered = export_service.run_export("staging", format="dotenv")

    assert active_profile == "staging"
    assert rendered == "APP_NAME=demo\n"
    assert "# Generated by envctl" not in rendered


def test_run_export_rejects_invalid_resolution(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(missing_required=("DATABASE_URL",))
    contract = make_contract({"DATABASE_URL": make_variable_spec(name="DATABASE_URL")})

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )

    with pytest.raises(ValidationError, match="Environment contract is not satisfied"):
        export_service.run_export("dev")


def test_run_export_rejects_unknown_keys(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo")},
        unknown_keys=("OLD_KEY",),
    )
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )

    with pytest.raises(ValidationError, match="Vault contains unknown keys"):
        export_service.run_export("dev")


def test_run_export_validates_and_projects_only_selected_group(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    contract = make_contract(
        {
            "API_HOST": make_variable_spec(name="API_HOST", group="Network"),
            "API_URL": make_variable_spec(name="API_URL", group="Application"),
        }
    )
    report = make_resolution_report(
        values={
            "API_HOST": make_resolved_value(key="API_HOST", value="host", source="profile"),
            "API_URL": make_resolved_value(key="API_URL", value="http://host", source="profile"),
        },
        missing_required=("API_HOST",),
        unknown_keys=("OLD_KEY",),
        invalid_keys=("API_HOST",),
    )

    monkeypatch.setattr(export_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(export_service, "load_contract_for_context", lambda _context: contract)
    monkeypatch.setattr(
        export_service,
        "resolve_environment",
        lambda _context, _contract, *, active_profile=None: report,
    )

    _context, _profile, rendered = export_service.run_export(
        "staging",
        format="dotenv",
        group="Application",
    )

    assert rendered == (
        "# ------------------------------------------------------------------\n"
        "# Application\n"
        "# ------------------------------------------------------------------\n"
        "API_URL=http://host\n"
    )
