from __future__ import annotations

from pathlib import Path

import pytest

import envctl.services.sync_service as sync_service
from envctl.errors import ValidationError
from envctl.services.projection_validation import ProjectionValidationDiagnostics
from tests.support.builders import make_resolution_report, make_resolved_value
from tests.support.contexts import make_project_context
from tests.support.contracts import make_contract, make_variable_spec
from tests.support.projection_validation import raise_projection_error


def test_run_sync_writes_generated_repo_env_file(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile"),
            "DATABASE_URL": make_resolved_value(
                key="DATABASE_URL",
                value="https://db.example.com",
                source="profile",
                masked=True,
            ),
        },
    )
    captured: dict[str, object] = {}
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME"),
            "DATABASE_URL": make_variable_spec(name="DATABASE_URL"),
        }
    )

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, group, operation: (contract, report),
    )
    monkeypatch.setattr(
        sync_service,
        "render_dotenv",
        lambda values, include_header=False, variable_groups=None: (
            "# Generated by envctl\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
            if include_header
            else "APP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
        ),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path = sync_service.run_sync("staging")

    assert active_profile == "staging"
    assert target_path == context.repo_root / ".env.staging"
    assert captured["path"] == context.repo_root / ".env.staging"
    assert (
        captured["text"]
        == "# Generated by envctl\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
    )


def test_run_sync_uses_custom_output_path_when_provided(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile")}
    )
    captured: dict[str, object] = {}
    output_path = Path("/tmp/custom/demo.env")
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, group, operation: (contract, report),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path = sync_service.run_sync(
        "staging",
        output_path=output_path,
    )

    assert active_profile == "staging"
    assert target_path == output_path
    assert captured["path"] == output_path
    assert captured["text"] == "# Generated by envctl\n\nAPP_NAME=demo\n"


def test_run_sync_body_matches_dotenv_export_except_for_header(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile"),
            "PORT": make_resolved_value(key="PORT", value="3000", source="default"),
        }
    )
    captured: dict[str, object] = {}
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME"),
            "PORT": make_variable_spec(name="PORT"),
        }
    )

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, group, operation: (contract, report),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    sync_service.run_sync("staging")

    sync_text = captured["text"]
    assert isinstance(sync_text, str)
    assert sync_text.startswith("# Generated by envctl\n")
    assert sync_text.removeprefix("# Generated by envctl\n\n") == "APP_NAME=demo\nPORT=3000\n"


def test_run_sync_rejects_invalid_resolution(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    filtered_report = make_resolution_report(missing_required=("DATABASE_URL",))

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, group, operation: (
            raise_projection_error(
                operation=operation,
                profile=active_profile,
                group=group,
                report=filtered_report,
                suggested_actions=("envctl fill", "envctl set KEY VALUE"),
            )
        ),
    )

    with pytest.raises(ValidationError, match="Cannot sync because") as exc_info:
        sync_service.run_sync("dev")

    assert exc_info.value.diagnostics == ProjectionValidationDiagnostics(
        operation="sync",
        active_profile="dev",
        selected_group=None,
        report=filtered_report,
        suggested_actions=("envctl fill", "envctl set KEY VALUE"),
    )


def test_run_sync_with_unknown_group_writes_only_generated_header(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME", group="Application")})
    report = make_resolution_report(
        values={"APP_NAME": make_resolved_value(key="APP_NAME", value="demo", source="profile")}
    )
    captured: dict[str, object] = {}

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, group, operation: (contract, report),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    sync_service.run_sync("staging", group="Missing")

    assert captured["text"] == "# Generated by envctl\n"
