from __future__ import annotations

import logging
from pathlib import Path

import pytest

import envctl.services.sync_service as sync_service
from envctl.domain.selection import group_selection
from envctl.errors import ValidationError
from tests.support.builders import make_resolution_report, make_resolved_value
from tests.support.contexts import make_project_context
from tests.support.contracts import make_contract, make_variable_spec
from tests.support.projection_validation import raise_projection_error


def test_run_sync_writes_generated_repo_env_file(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            ),
            "DATABASE_URL": make_resolved_value(
                key="DATABASE_URL",
                value="https://db.example.com",
                source="profile",
                masked=True,
            ),
        },
    )
    captured: dict[str, object] = {}
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME"),
            "DATABASE_URL": make_variable_spec(name="DATABASE_URL"),
        }
    )

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path, warnings = sync_service.run_sync("staging")

    assert active_profile == "staging"
    assert warnings == ()
    assert target_path == context.repo_root / ".env.staging"
    assert captured["path"] == context.repo_root / ".env.staging"
    assert captured["text"] == (
        "# Generated by envctl\n\nAPP_NAME=demo\nDATABASE_URL=https://db.example.com\n"
    )


def test_run_sync_uses_custom_output_path_when_provided(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            )
        }
    )
    captured: dict[str, object] = {}
    output_path = Path("/tmp/custom/demo.env")
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    _context, active_profile, target_path, _warnings = sync_service.run_sync(
        "staging",
        output_path=output_path,
    )

    assert active_profile == "staging"
    assert target_path == output_path
    assert captured["path"] == output_path
    assert captured["text"] == "# Generated by envctl\n\nAPP_NAME=demo\n"


def test_run_sync_rejects_invalid_resolution(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context()
    filtered_report = make_resolution_report(missing_required=("DATABASE_URL",))

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: raise_projection_error(
            operation=operation,
            profile=active_profile,
            selection=selection,
            report=filtered_report,
            suggested_actions=("envctl fill", "envctl set KEY VALUE"),
        ),
    )

    with pytest.raises(ValidationError, match=r"Cannot sync because"):
        sync_service.run_sync("dev")


def test_run_sync_filters_values_by_group_selection(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    contract = make_contract(
        {
            "APP_NAME": make_variable_spec(name="APP_NAME", groups=("Application",)),
            "SECRET": make_variable_spec(name="SECRET", groups=("Secrets",)),
        }
    )
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            ),
            "SECRET": make_resolved_value(
                key="SECRET",
                value="top",
                source="profile",
                masked=True,
            ),
        }
    )
    captured: dict[str, object] = {}

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )
    monkeypatch.setattr(
        sync_service,
        "write_text_atomic",
        lambda path, text: captured.update({"path": path, "text": text}),
    )

    sync_service.run_sync("staging", selection=group_selection("Application"))

    assert captured["text"] == (
        "# Generated by envctl\n"
        "\n"
        "# ------------------------------------------------------------------\n"
        "# Application\n"
        "# ------------------------------------------------------------------\n"
        "APP_NAME=demo\n"
    )


def test_run_sync_logs_info_when_writing_output(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
) -> None:
    context = make_project_context(repo_env_path="/tmp/demo/.env.local")
    contract = make_contract({"APP_NAME": make_variable_spec(name="APP_NAME")})
    report = make_resolution_report(
        values={
            "APP_NAME": make_resolved_value(
                key="APP_NAME",
                value="demo",
                source="profile",
            )
        }
    )

    monkeypatch.setattr(sync_service, "load_project_context", lambda: (object(), context))
    monkeypatch.setattr(
        sync_service,
        "resolve_projectable_environment",
        lambda _context, *, active_profile, selection, operation: (
            contract,
            report,
            (),
        ),
    )
    monkeypatch.setattr(sync_service, "write_text_atomic", lambda path, text: None)

    logger = logging.getLogger("envctl")
    logger.addHandler(caplog.handler)
    logger.setLevel(logging.INFO)
    caplog.set_level("INFO")

    try:
        sync_service.run_sync("staging")
    finally:
        logger.removeHandler(caplog.handler)

    messages = [
        record.message
        for record in caplog.records
        if record.name == "envctl.services.sync_service" and record.levelname == "INFO"
    ]
    assert messages == [
        "Writing synced environment file",
        "Synced environment file written",
    ]
